libnm-glib-aux: don't undefine GLib macros
NetworkManager defines its own NM_MIN()/NM_MAX() macros which offer
some advantages over the MIN()/MAX() from GLib: arguments are
evaluated only once and mixed signed/unsigned comparisons are
rejected, while still preserving compile time evaluation for constant
values.

To prevent the usage of the GLib macros, they were undefined in
nm-glib.h. However, this can cause compilation errors if the public
GLib headers use them:

  /usr/include/glib-2.0/glib/gslice.h:48:57: error: implicit declaration of function ‘MAX’ [-Wimplicit-function-declaration]
     48 | #define  g_slice_new(type)      ((type*) g_slice_alloc (MAX (sizeof (type), 1)))
      |                                                         ^~~
  ../src/libnm-glib-aux/nm-dbus-aux.c:652:23: note: in expansion of macro ‘g_slice_new’
    652 |     sd              = g_slice_new(NMDBusSignalData);
        |                       ^~~~~~~~~~~

Don't undefine the macros but add checkpatch rules to verify the NM
variants are used. Use a similar approach for other macros.

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/work_items/1911