cli: fix warning about uninitialized value
gcc warns:

    make[4]: Entering directory `./NetworkManager/cli/src'
      CC       connections.o
    connections.c: In function ‘complete_connection_by_type’:
    connections.c:4235:18: error: ‘mtu_int’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         g_object_set (s_wired, NM_SETTING_WIRED_MTU, mtu_int, NULL);
                      ^

Signed-off-by: Thomas Haller <thaller@redhat.com>
(cherry picked from commit f0d40201aecf94e77312e0813a25b93faae093f6)