device: fix build with old glib & more asserts
  src/devices/nm-device.c:8319:4: error: invalid use of void expression

(cherry picked from commit a4d61bf29905ac9e5c7e6f99344733a4ccb2297f)