bluez: fix compiler error due to redefinition of typedef
clang warns:
    make[5]: Entering directory `./NetworkManager/src/devices/bluetooth'
      CC       nm-bluez5-dun.lo
    nm-bluez5-dun.c:50:3: error: redefinition of typedef 'NMBluez5DunContext' is a C11 feature [-Werror,-Wtypedef-redefinition]
    } NMBluez5DunContext;
      ^
    ./nm-bluez5-dun.h:27:36: note: previous definition is here
    typedef struct _NMBluez5DunContext NMBluez5DunContext;
                                       ^

Fixes: f1c9595311f52d8b79e8d2032e006005613a8fb1
Signed-off-by: Thomas Haller <thaller@redhat.com>
(cherry picked from commit d5ceb0af1582283867cf9a73cb1443fab0f1c9e9)