dhcp: drop unused variable
src/dhcp/nm-dhcp-client.c:552:16: error: unused variable 'str' [-Werror,-Wunused-variable]
        gs_free char *str = NULL;
                      ^

Fixes: 787f4b57cda7ba03fde412bb7693baf8f5f67ef5
(cherry picked from commit 6f111b3d2e8348ed8eee6da532ae8da994d28d19)