cli: fix an bug when reporting an error
$ nmcli dev wifi rescan ifname eteee

(process:21211): libnm-CRITICAL **: nm_device_get_device_type: assertion 'NM_IS_DEVICE (self)' failed
Error: Device 'eteee' is not a Wi-Fi device.

Fixes: 823df334eda48a8e2cec897d6123f7b2158c12ff
(cherry picked from commit bccc1af51b768cd5a2f9268f6cf57d5cc06a9a54)