manager: drop an unused variable
src/nm-manager.c:5857:36: error: unused variable 'object' [-Werror,-Wunused-variable]
        gs_unref_object NMExportedObject *object = NULL;
                                          ^