glib-aux: avoid compiler warning about ignoring getrandom() result
  src/libnm-glib-aux/nm-random-utils.c:112:12: error: ignoring return value of 'getrandom' declared with attribute 'warn_unused_result' [-Werror=unused-result]

Fixes: 18597e33cbfc ('glib-aux: also use getrandom() for seeding pseudo random generator')
(cherry picked from commit 11d59f81cfb303303416de3707cf793dede31896)