cli: remove unused static struct nmc_mobile_settings
clang warns:

    make[4]: Entering directory `./NetworkManager/cli/src'
      CC       connections.o
    connections.c:2206:23: error: unused variable 'nmc_mobile_settings' [-Werror,-Wunused-const-variable]
    static const NameItem nmc_mobile_settings [] = {
                          ^

Signed-off-by: Thomas Haller <thaller@redhat.com>
(cherry picked from commit 996b31ec20988eed92399f6495c13dd92c38076b)