sleep-monitor-upower: add missing include
Otherwise building fails with:

  nm-sleep-monitor-upower.c:132:45: error: expected declaration specifiers or '...' before 'nm_sleep_monitor_get'
  nm-sleep-monitor-upower.c:132:67: error: expected declaration specifiers or '...' before '(' token

https://mail.gnome.org/archives/networkmanager-list/2016-May/msg00053.html