build: fix build dependency for generating libnm enum headers before building nm-online
      CC       clients/nm_online-nm-online.o
    In file included from ./shared/nm-default.h:311:0,
                     from clients/nm-online.c:34:
    ./libnm/NetworkManager.h:60:10: fatal error: nm-enum-types.h: No such file or directory
     #include "nm-enum-types.h"
              ^~~~~~~~~~~~~~~~~

(cherry picked from commit d8070c7a148c8867db149aa09a61cc59fd5e47bb)
(cherry picked from commit a79d9dacf133ac3811fa48230f348ea9a89c36ca)