core: fix builds without polkit support
Fix the following build error:

 nm-auth-utils.c: In function ‘nm_auth_chain_add_call’:
 nm-auth-utils.c:402:46: error: ‘DBUS_GERROR’ undeclared (first use in this function)
     call->chain->error = g_error_new_literal (DBUS_GERROR,

Fixes: 1cf35cb26b6cc04f8b2c51c3cde4bc08ef311062
(cherry picked from commit b9e89c918f13374772a72cefbe0cda6bb6bc88e4)