libnm: avoid "-Walloc-size" warning in nm_team_link_watcher_new_ethtool()
gcc-14.0.1-0.2.fc40 warns:

    CC       src/libnm-core-impl/libnm_core_impl_la-nm-setting-team.lo
  ../src/libnm-core-impl/nm-setting-team.c: In function nm_team_link_watcher_new_ethtool:
  ../src/libnm-core-impl/nm-setting-team.c:127:13: error: allocation of insufficient size 16 for type NMTeamLinkWatcher with size 48 [-Werror=alloc-size]
    127 |     watcher = g_malloc(nm_offsetofend(NMTeamLinkWatcher, ethtool));
        |             ^

(cherry picked from commit 5715feebe728b25cb36a1a40808c0386794db9f5)
(cherry picked from commit eaa3a4e396a36b29897ef7862fe0d3f79aebd728)
(cherry picked from commit 571273f71cc2f7fdba3d5c49ab7eef198e23a2c4)
(cherry picked from commit c6643546f4728ff6428a10b33fe766b5898c2a27)