libnm-core/tests: fix compiler warning about unused variable
    make[5]: Entering directory './NetworkManager/libnm-core/tests'
      CC       test-general.o
    test-general.c:3776:24: error: unused variable 'error' [-Werror,-Wunused-variable]
            gs_free_error GError *error = NULL;
                                  ^