libnl-util: refactor nm_utils_ip4_prefix_to_netmask/netmask_to_prefix
- use a more efficient implementation for prefix_to_netmask
- fix netmask_to_prefix to behave consistently in case of
  invalid netmask
- remove unused duplicated functions from NetworkManagerUtils.c
- add test functions

Based-on-patch-by: Pavel Šimerda <psimerda@redhat.com>
Signed-off-by: Thomas Haller <thaller@redhat.com>
Related: https://bugzilla.gnome.org/show_bug.cgi?id=721771

(cherry picked from commit 4dd6ab8f4b47e906be84442be8d68e82e41a1a24)

Backport this commit, because the previous implementation of
nm_utils_ip4_netmask_to_prefix caused a compiler warning:

  nm-utils.c: In function 'nm_utils_ip4_netmask_to_prefix':
  nm-utils.c:1676:22: error: assuming pointer wraparound does not occur when comparing P +- C1 with P +- C2 [-Werror=strict-overflow]
    while ((*p == 0xFF) && p < end) {