cli: support escaping delimiters for "connection.seconaries"
It's obviously a change in behavior. Now accept backslash for escaping
the whitespace+comma separators when setting "connection.secondaries".

Before:

  $ nmcli --offline connection add type ethernet con-name x connection.secondaries 'a b'
  Error: failed to modify connection.secondaries: the value 'a' is not a valid UUID.
  $ nmcli --offline connection add type ethernet con-name x connection.secondaries 'a\ b'
  Error: failed to modify connection.secondaries: the value 'a\' is not a valid UUID.

After:

  $ nmcli --offline connection add type ethernet con-name x connection.secondaries 'a\ b'
  Error: failed to modify connection.secondaries: the value 'a b' is not a valid UUID.

https://bugzilla.redhat.com/show_bug.cgi?id=2177209