nm-sudo: fix printf format string in _handle_ping()
src/nm-sudo/nm-sudo.c: In function '_handle_ping':
src/nm-sudo/nm-sudo.c:92:79: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'gint64' {aka 'long long int'} [-Werror=format=]
   92 |     msg = g_strdup_printf("pid=%lu, unique-name=%s, nm-name-owner=%s, since=%ld.%03d%s, pong=%s",
      |                                                                             ~~^
      |                                                                               |
      |                                                                               long int
      |                                                                             %lld
......
   96 |                           running_msec / 1000,
      |                           ~~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        gint64 {aka long long int}

Fixes: f137b32d3117 ('sudo: introduce nm-sudo D-Bus service')