ifnet: avoid compiler warning about casting function pointers
  ../../src/settings/plugins/ifnet/nms-ifnet-plugin.c: In function ‘monitor_file_changes’:
  ../../src/settings/plugins/ifnet/nms-ifnet-plugin.c:140:42: error: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, GObject *)’ {aka ‘void (*)(void *, struct _GObject *)’} [-Werror=cast-function-type]
     g_object_weak_ref (G_OBJECT (monitor), (GWeakNotify) g_free,
                                            ^

(cherry picked from commit dccc449522aa7e5590da74a9be92afe02bae20d7)
(cherry picked from commit d7170e21fcf888ccbbc28141416102443c752f96)