device: fix casting pointer to enum for sriov_reset_on_deactivate_cb()
Avoids a compiler warning:

    ../src/devices/nm-device.c:16079:26: error: cast to smaller integer type 'NMDeviceStateReason' from 'gpointer' (aka 'void *') [-Werror,-Wvoid-pointer-to-enum-cast]
            deactivate_ready (self, (NMDeviceStateReason) reason);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 121c58f0c48d ('core: set number of SR-IOV VFs asynchronously')
(cherry picked from commit 918ebd600acba97ea64af7d1039339983fa44af4)
(cherry picked from commit 32641b9fca45f29372d76f06fcb9330e14820b15)
(cherry picked from commit c24888be5113f459a2d0af6e49998b52b2b7196c)
(cherry picked from commit 3d27459460433f17d5402ca9d15db49f5e321b7b)