libnm-core: empty key is not a pkcs12 file
  nmcli> set 802-1x.ca-cert file:///tmp/certs/eaptest_ca_cert.pem
  (process:31015): libnm-CRITICAL **: crypto_is_pkcs12_data: assertion 'data != NULL' failed
  Error: failed to set 'ca-cert' property: PEM certificate had no start tag '-----BEGIN CERTIFICATE-----'.

(cherry picked from commit 1d66d415b8d8bc031f68bf4fc04c131cef3a5d30)