ifcfg-rh: drop an unused variable
  nms-ifcfg-rh-reader.c:497:25: error: unused variable 'local_error' [-Werror,-Wunused-variable]
                gs_free_error GError *local_error = NULL;
                                      ^

Fixes: 40e1fd9531119318dfc05b6fdab0c326b60f9bdd