contrib/rpm: fix spec file using bare words
  error: bare words are no longer supported, please use "...":  no != yes
  error: /builds/NetworkManager/NetworkManager/contrib/fedora/rpm/NetworkManager.20200418-163008.VM582H/SPECS/NetworkManager.spec:596: bad %if condition:  no != yes

(cherry picked from commit be78a1201290fdd49b206fc06d3a4127e762b571)
(cherry picked from commit c869d792a218caf9a5ed09f8f71d2527452244dd)
(cherry picked from commit 5735e267cd0f0bffa9a8fd97ed472ca0ce8ddc63)