initrd: fix compilation error
../src/core/initrd/tests/test-cmdline-reader.c:461:36: error: unused variable 'connections' [-Werror,-Wunused-variable]
    gs_unref_hashtable GHashTable *connections = NULL;
                                   ^

Fixes: c27626a0ce4d ('initrd: set multi-connect=single for connections with static IP')
(cherry picked from commit c907fecbc5946ab8c9077d19ecba615d873d1810)