firewall: avoid invalid -Werror=maybe-uninitialized warning in _handle_dbus_start()
    ../../src/nm-firewall-manager.c: In function ‘_handle_dbus_start’:
    ../../src/nm-firewall-manager.c:318:2: error: ‘dbus_method’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      g_dbus_proxy_call (priv->proxy,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         dbus_method,
                         ~~~~~~~~~~~~
                         arg,
                         ~~~~

Fixes: d8bf05d3e695f043eeb0fac4646fc6babad1bee3
(cherry picked from commit 3ba614d6963fb7d21b93f591ae60ec2a06a8e281)