cli: fix missing newline for printing error message about "Connection deletion failed"
  $ nmcli connection delete Wired\ connection\ 1
  Error: Connection deletion failed: Insufficient privilegesError: not all connections deleted.