core: avoid compiler warnings in write_to_netconfig() and ifnet_update_parsers_by_connection()
    src/dns/nm-dns-manager.c: In function ‘write_to_netconfig’:
    src/dns/nm-dns-manager.c:387:8: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
      write (fd, str, strlen (str));
            ^

    src/settings/plugins/ifnet/nms-ifnet-connection-parser.c: In function ‘ifnet_update_parsers_by_connection’:
    src/settings/plugins/ifnet/nms-ifnet-connection-parser.c:2600:26: error: variable ‘pppoe’ set but not used [-Werror=unused-but-set-variable]
      gboolean wired = FALSE, pppoe = TRUE;
                              ^~~~~

While at it, don't log line breaks in ifnet_update_parsers_by_connection().

Fixes: e912b36d95a3c26a6021eeb27e663bd05910a9b4