core: don't add connections if the feature is disabled at build time
If teaming, Wi-Fi, OVS, WWAN support is disabled at build time, it is
better to report an error when the connection is added via nmcli (or
loaded from disk) than accepting the connection and complaining later
about a "missing plugin"; there is no plugin because it wasn't built.

Example errors now:
  # nmcli connection add type team
  Error: Failed to add 'team-nm-team' connection: team support is disabled in this build

  # nmcli connection add type gsm
  Error: Failed to add 'gsm' connection: WWAN support is disabled in this build