clients: fix build with old GLib
G_DEFINE_QUARK is only available since 2.34, include
"nm-glib-compat.h" to fix the following error:

 ./../common/nm-vpn-helpers.c: In function ‘G_DEFINE_QUARK’:
 ./../common/nm-vpn-helpers.c:54:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token

Fixes: dca2ded7e8bd38eaed7e1e79f92cbfa10917d493