build: fix -Wignored-qualifiers warnings
    ./src/nm-config-data.h:163:1: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
    const guint nm_config_data_get_connectivity_interval (const NMConfigData *config_data);
    ^~~~~~

(cherry picked from commit e68cc17f438b555e3d69603ffe12c01add732ffb)