device: fix compile error in _set_State_full() for missing cast
    src/devices/nm-device.c: In function '_set_state_full':
    src/devices/nm-device.c:14766:19: error: assignment from incompatible pointer type [-Werror]
       if (   (s_sriov = nm_device_get_applied_setting (self, NM_TYPE_SETTING_SRIOV))
                       ^

Fixes: 6ae1f64351f326a18c9654b4b8cf5c0dfedb0951