nmcli: support "PORT" with --fields option
When the --fields is used, nmcli must accept PORT and also suggest it if
an invalid field is introduced.

```
nmcli --fields UUID,PORT conn show
Error: invalid field 'PORT'; allowed fields: NAME,UUID,TYPE,TIMESTAMP,TIMESTAMP-REAL,AUTOCONNECT,AUTOCONNECT-PRIORITY,READONLY,DBUS-PATH,ACTIVE,DEVICE,STATE,ACTIVE-PATH,SLAVE,FILENAME.
```