device: drop unused variable and avoid compiler warning
  ../src/core/devices/nm-device-ethernet.c:1164:35: error: unused variable error [-Werror,-Wunused-variable]
              gs_free_error GError *error    = NULL;
                                    ^

Fixes: aa9b5e28eb6d ('ethernet: fix setting ip-ifindex for PPPoE connections')