core/tests: remove an unused variable
  test-general.c:6612:19: error: unused variable 'buf_free_1'
                                 [-Werror,-Wunused-variable]
        gs_free gpointer buf_free_1 = NULL;

(cherry picked from commit e732789bbfad6f4824d66a6ed76e40f8d907e846)