nmtui: fix wrong use of assertions in bond page
When building in release mode the compiler complains with:

  ../src/nmtui/nmt-page-bond.c: In function ‘other_options_widget_changed’:
  ../src/nmtui/nmt-page-bond.c:373:13: error: ‘name’ may be used uninitialized [-Werror=maybe-uninitialized]
    373 |         if (_is_other_option(name)) {
        |             ^~~~~~~~~~~~~~~~~~~~~~
  ../src/nmtui/nmt-page-bond.c:357:25: note: ‘name’ was declared here
    357 |     const char         *name;
        |                         ^~~~

That happens because "name" is initialized inside an assertion, which
is removed in release builds. Assertions must not have side effects.

Move the initialization out of the assertion.

Fixes: 6a841072ec3b ('nmtui/bond: introduce "other options" list')