test-common: drop unused variables
src/platform/tests/test-common.c:1500:17: error: unused variable 'dev' [-Werror,-Wunused-variable]
                gs_free char *dev = NULL;
                              ^
src/platform/tests/test-common.c:1501:17: error: unused variable 'local' [-Werror,-Wunused-variable]
                gs_free char *local = NULL, *remote = NULL;
                              ^
src/platform/tests/test-common.c:1501:32: error: unused variable 'remote' [-Werror,-Wunused-variable]
                gs_free char *local = NULL, *remote = NULL;
                                             ^
Fixes: bd8ab54b8e2f66a53971430d66db766ca30b18ad